import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f7f5ef',
  },
  loadingShell: {
    alignItems: 'center',
    flex: 1,
    gap: 14,
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: '#33413c',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
  },
  appShell: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  authShell: {
    flexGrow: 1,
    gap: 18,
    justifyContent: 'center',
    padding: 20,
  },
  authHeader: {
    gap: 6,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  headerIdentity: {
    flex: 1,
  },
  eyebrow: {
    color: '#5a635f',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#15211d',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 3,
  },
  authTitle: {
    color: '#15211d',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0,
  },
  subtitle: {
    color: '#4d5753',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 4,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#cfc8bb',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  logoutText: {
    color: '#2b3834',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  householdStrip: {
    backgroundColor: '#e9e3d8',
    borderRadius: 8,
    marginBottom: 12,
    minHeight: 42,
    padding: 10,
  },
  householdStripText: {
    color: '#59615e',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statusBanner: {
    backgroundColor: '#eef3f8',
    borderColor: '#b8c8d6',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 11,
  },
  statusBannerSuccess: {
    backgroundColor: '#eef8f2',
    borderColor: '#aacdb8',
  },
  statusBannerError: {
    backgroundColor: '#fff0ed',
    borderColor: '#ebb2a5',
  },
  statusBannerText: {
    color: '#33413c',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 18,
  },
  statusBannerTextError: {
    color: '#8a2f20',
  },
  householdChips: {
    gap: 8,
    paddingBottom: 12,
  },
  householdChip: {
    backgroundColor: '#e9e3d8',
    borderColor: '#d2c9ba',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 13,
  },
  householdChipActive: {
    backgroundColor: '#ffffff',
    borderColor: '#9dbba9',
  },
  householdChipText: {
    color: '#59615e',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  householdChipTextActive: {
    color: '#15211d',
  },
  modeSwitch: {
    backgroundColor: '#e9e3d8',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  modeButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  modeButtonActive: {
    backgroundColor: '#ffffff',
  },
  modeText: {
    color: '#59615e',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  modeTextActive: {
    color: '#15211d',
  },
  form: {
    gap: 14,
  },
  formPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  inputGroup: {
    gap: 7,
  },
  inputLabel: {
    color: '#24312d',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#cfc8bb',
    borderRadius: 8,
    borderWidth: 1,
    color: '#15211d',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  errorBox: {
    backgroundColor: '#fff0ed',
    borderColor: '#ebb2a5',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  errorText: {
    color: '#8a2f20',
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#1d7f68',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0,
  },
  buttonPressed: {
    opacity: 0.82,
  },
  buttonDisabled: {
    opacity: 0.58,
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#1d7f68',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 11,
  },
  smallButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  smallDangerButton: {
    alignItems: 'center',
    backgroundColor: '#fff0ed',
    borderColor: '#ebb2a5',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 10,
  },
  smallDangerText: {
    color: '#8a2f20',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  tabBar: {
    backgroundColor: '#e9e3d8',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 6,
  },
  tabActive: {
    backgroundColor: '#ffffff',
  },
  tabLabel: {
    color: '#59615e',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  tabLabelActive: {
    color: '#15211d',
  },
  content: {
    gap: 18,
    paddingBottom: 32,
    paddingTop: 18,
  },
  surfaceBand: {
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderLeftWidth: 5,
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  surfaceTitle: {
    color: '#15211d',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
  },
  surfaceSummary: {
    color: '#4d5753',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    color: '#24312d',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statTile: {
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    padding: 14,
  },
  statValue: {
    color: '#15211d',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statLabel: {
    color: '#56615d',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 2,
  },
  profilePanel: {
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 16,
  },
  profileName: {
    color: '#15211d',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  profileMeta: {
    color: '#56615d',
    fontSize: 14,
    lineHeight: 20,
  },
  listBlock: {
    gap: 10,
  },
  shoppingListChips: {
    gap: 8,
  },
  listChip: {
    backgroundColor: '#f4f0e8',
    borderColor: '#d2c9ba',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  listChipActive: {
    backgroundColor: '#ffffff',
    borderColor: '#946200',
  },
  listChipText: {
    color: '#59615e',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  listChipTextActive: {
    color: '#15211d',
  },
  listHeader: {
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  entityRow: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 14,
  },
  entityRowHighlighted: {
    borderColor: '#c78b00',
    borderWidth: 2,
  },
  entityCopy: {
    flex: 1,
    gap: 3,
  },
  rowActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  entityTitle: {
    color: '#15211d',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
  },
  entityMeta: {
    color: '#59615e',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  hintText: {
    color: '#6c746f',
    fontSize: 13,
    lineHeight: 18,
  },
  dataPanel: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 14,
  },
  dataCopy: {
    flex: 1,
    gap: 4,
  },
  dataTitle: {
    color: '#15211d',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
  },
  dataBody: {
    color: '#56615d',
    fontSize: 14,
    lineHeight: 20,
  },
  statePanel: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#ded8cd',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  feedbackPanel: {
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  feedbackPanelSuccess: {
    backgroundColor: '#eef8f2',
    borderColor: '#aacdb8',
  },
  feedbackPanelError: {
    backgroundColor: '#fff0ed',
    borderColor: '#ebb2a5',
  },
  feedbackTextSuccess: {
    color: '#1d553d',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  feedbackTextError: {
    color: '#8a2f20',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  stateText: {
    color: '#33413c',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: '#1d7f68',
    borderRadius: 8,
    minHeight: 40,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  checkDot: {
    borderRadius: 5,
    height: 10,
    marginTop: 5,
    width: 10,
  },
});
