import { StyleSheet } from 'react-native';

export const mobileColors = {
  amber: '#E8A055',
  amberSoft: '#FDF4E8',
  amberText: '#6B430E',
  borderSubtle: '#E0DDD8',
  borderWarm: '#EAD7C3',
  blueGray: '#5B8FC4',
  blueGraySoft: '#E8F1F8',
  charcoal: '#1A1A1A',
  cream: '#F5F2ED',
  danger: '#B75B4A',
  dangerSoft: '#FFF0ED',
  green: '#6B8E5E',
  greenSoft: '#E8F0E5',
  mutedGray: '#6F6A62',
  neutralSoft: '#EFE8DC',
  pressed: '#EBE8E3',
  quiet: '#F9F7F4',
  teal: '#2F7D6D',
  tealDark: '#23665A',
  terracotta: '#C45A3B',
  white: '#FFFDF8',
};

export const commandToneColors = {
  idle: mobileColors.borderWarm,
  thinking: mobileColors.amber,
  executed: mobileColors.green,
  scheduled: mobileColors.green,
  needs_input: mobileColors.blueGray,
  needs_confirmation: mobileColors.amber,
  rejected: mobileColors.danger,
  degraded: '#9C8262',
};

const softShadow = {
  elevation: 3,
  shadowColor: '#1A1A1A',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.08,
  shadowRadius: 22,
};

const heroShadow = {
  elevation: 4,
  shadowColor: '#1A1A1A',
  shadowOffset: { width: 0, height: 10 },
  shadowOpacity: 0.08,
  shadowRadius: 26,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: mobileColors.cream,
  },
  loadingShell: {
    alignItems: 'center',
    flex: 1,
    gap: 14,
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: mobileColors.charcoal,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
  },
  appShell: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 12,
  },
  authShell: {
    flexGrow: 1,
    gap: 18,
    justifyContent: 'center',
    padding: 20,
  },
  authHeader: {
    gap: 6,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerIdentity: {
    flex: 1,
  },
  eyebrow: {
    color: mobileColors.teal,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: mobileColors.charcoal,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 34,
    marginTop: 2,
  },
  authTitle: {
    color: mobileColors.charcoal,
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 0,
  },
  subtitle: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 3,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  logoutText: {
    color: mobileColors.mutedGray,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  householdStrip: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 10,
    minHeight: 42,
    padding: 10,
  },
  householdStripText: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statusBanner: {
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  statusBannerSuccess: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  statusBannerError: {
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
  },
  statusBannerText: {
    color: mobileColors.charcoal,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 18,
  },
  statusBannerTextError: {
    color: '#8A2F20',
  },
  householdChips: {
    gap: 8,
    paddingBottom: 12,
  },
  householdChip: {
    backgroundColor: mobileColors.quiet,
    borderColor: '#EADFD2',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 13,
  },
  householdChipActive: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  householdChipText: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  householdChipTextActive: {
    color: mobileColors.teal,
  },
  modeSwitch: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  modeButton: {
    alignItems: 'center',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  modeButtonActive: {
    backgroundColor: mobileColors.greenSoft,
  },
  modeText: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  modeTextActive: {
    color: mobileColors.teal,
  },
  form: {
    gap: 14,
  },
  formPanel: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  inputGroup: {
    gap: 7,
  },
  inputLabel: {
    color: mobileColors.charcoal,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7D0C5',
    borderRadius: 18,
    borderWidth: 1,
    color: mobileColors.charcoal,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  inputMultiline: {
    minHeight: 92,
    paddingTop: 13,
  },
  errorBox: {
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
  },
  errorText: {
    color: '#8A2F20',
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.teal,
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.quiet,
    borderColor: '#EADFD2',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  buttonPressed: {
    opacity: 0.82,
  },
  buttonDisabled: {
    opacity: 0.58,
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.teal,
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  smallButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  smallDangerButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  smallDangerText: {
    color: '#8A2F20',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  bottomNavigation: {
    paddingBottom: 12,
    paddingTop: 10,
  },
  tabBar: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 4,
  },
  tabActive: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
    borderWidth: 1,
  },
  tabLabel: {
    color: mobileColors.mutedGray,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  tabLabelActive: {
    color: mobileColors.teal,
  },
  content: {
    gap: 12,
    paddingBottom: 12,
    paddingTop: 12,
  },
  surfaceBand: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderWarm,
    borderLeftWidth: 0,
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    ...softShadow,
  },
  surfaceTitle: {
    color: mobileColors.charcoal,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 33,
  },
  surfaceSummary: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  section: {
    gap: 12,
  },
  sectionTight: {
    gap: 8,
  },
  sectionTitle: {
    color: mobileColors.charcoal,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statTile: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 15,
    borderWidth: 1,
    flexBasis: '30%',
    flexGrow: 1,
    minHeight: 62,
    padding: 10,
  },
  statValue: {
    color: mobileColors.charcoal,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statLabel: {
    color: mobileColors.mutedGray,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 2,
  },
  profilePanel: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 18,
    borderWidth: 1,
    gap: 5,
    padding: 14,
  },
  profileName: {
    color: mobileColors.charcoal,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  profileMeta: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    lineHeight: 20,
  },
  listBlock: {
    gap: 10,
  },
  shoppingListChips: {
    gap: 8,
  },
  listChip: {
    backgroundColor: mobileColors.quiet,
    borderColor: '#EADFD2',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  listChipActive: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  listChipText: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  listChipTextActive: {
    color: mobileColors.teal,
  },
  listHeader: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
  },
  entityRow: {
    alignItems: 'flex-start',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 12,
  },
  entityRowHighlighted: {
    borderColor: mobileColors.amber,
    borderWidth: 2,
  },
  entityCopy: {
    flex: 1,
    gap: 3,
  },
  rowActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  entityTitle: {
    color: mobileColors.charcoal,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 20,
  },
  entityMeta: {
    color: mobileColors.mutedGray,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 17,
  },
  hintText: {
    color: mobileColors.mutedGray,
    fontSize: 12,
    lineHeight: 17,
  },
  softCard: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  softCardElevated: {
    ...softShadow,
  },
  dataPanel: {
    alignItems: 'flex-start',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 14,
  },
  dataPanelSuccess: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  dataPanelClarify: {
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
  },
  dataPanelConfirm: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
  },
  dataPanelReject: {
    backgroundColor: '#FFF8F5',
    borderColor: '#F2C1B1',
  },
  dataPanelDegraded: {
    backgroundColor: mobileColors.neutralSoft,
    borderColor: '#CDBFAE',
  },
  confirmationPanel: {
    alignItems: 'flex-start',
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 14,
    ...softShadow,
  },
  confirmationBlock: {
    gap: 4,
    marginTop: 8,
  },
  confirmationChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  confirmationChip: {
    backgroundColor: mobileColors.white,
    borderColor: '#F3D7B0',
    borderRadius: 999,
    borderWidth: 1,
    color: mobileColors.amberText,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  confirmationActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  confirmationButton: {
    flexGrow: 1,
    minWidth: 130,
  },
  dataCopy: {
    flex: 1,
    gap: 5,
  },
  dataTitle: {
    color: mobileColors.charcoal,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 21,
  },
  dataBody: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    lineHeight: 20,
  },
  statePanel: {
    alignItems: 'center',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  feedbackPanel: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
  },
  feedbackPanelSuccess: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  feedbackPanelError: {
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
  },
  feedbackTextSuccess: {
    color: '#1D553D',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  feedbackTextError: {
    color: '#8A2F20',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  stateText: {
    color: mobileColors.charcoal,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.teal,
    borderRadius: 999,
    minHeight: 40,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  checkDot: {
    borderRadius: 5,
    height: 10,
    marginTop: 5,
    width: 10,
  },
  commandHero: {
    alignItems: 'center',
    borderColor: mobileColors.borderWarm,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 142,
    padding: 18,
    ...heroShadow,
  },
  commandHeroIdle: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderWarm,
  },
  commandHeroThinking: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: mobileColors.borderWarm,
  },
  commandHeroExecuted: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  commandHeroNeedsInput: {
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
  },
  commandHeroConfirm: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
  },
  commandHeroRejected: {
    backgroundColor: '#FFF8F5',
    borderColor: '#F2C1B1',
  },
  commandHeroDegraded: {
    backgroundColor: mobileColors.neutralSoft,
    borderColor: '#CDBFAE',
  },
  commandHeroCopy: {
    flex: 1,
    gap: 6,
  },
  commandHeroTitle: {
    color: mobileColors.charcoal,
    fontSize: 21,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 25,
  },
  commandHeroBody: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    lineHeight: 18,
  },
  commandComposer: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  commandComposerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  commandSubmitButton: {
    flex: 1,
  },
  commandExamples: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  voiceMicButton: {
    alignItems: 'center',
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 64,
    paddingHorizontal: 14,
  },
  voiceMicButtonText: {
    color: '#2B587C',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  voiceDraftBanner: {
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
    borderRadius: 16,
    borderWidth: 1,
    padding: 10,
  },
  voiceDraftText: {
    color: '#2B587C',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 17,
  },
  voiceSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  voiceSheetScrim: {
    backgroundColor: 'rgba(26, 26, 26, 0.32)',
    flex: 1,
  },
  voiceSheet: {
    backgroundColor: mobileColors.cream,
    borderColor: mobileColors.borderWarm,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    gap: 14,
    padding: 18,
    ...heroShadow,
  },
  voiceSheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#D2C8BB',
    borderRadius: 999,
    height: 4,
    width: 44,
  },
  voiceSheetHeader: {
    gap: 6,
  },
  voiceSheetTitle: {
    color: mobileColors.charcoal,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 26,
  },
  voiceSheetBody: {
    color: mobileColors.mutedGray,
    fontSize: 14,
    lineHeight: 20,
  },
  voiceRecordingPanel: {
    alignItems: 'center',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    padding: 18,
  },
  voicePulse: {
    backgroundColor: mobileColors.danger,
    borderRadius: 12,
    height: 24,
    width: 24,
  },
  voiceTimer: {
    color: mobileColors.charcoal,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
  },
  voiceReviewCard: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    padding: 14,
  },
  voiceProcessingCard: {
    alignItems: 'center',
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  voiceStatusText: {
    color: mobileColors.amberText,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  voiceErrorCard: {
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  voiceSheetActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  voiceSheetActionButton: {
    flexGrow: 1,
    minWidth: 130,
  },
  exampleChip: {
    backgroundColor: '#F7F1E7',
    borderColor: mobileColors.borderSubtle,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  exampleChipText: {
    color: mobileColors.mutedGray,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statePill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  statePillIdle: {
    backgroundColor: mobileColors.quiet,
    borderColor: mobileColors.borderSubtle,
  },
  statePillSuccess: {
    backgroundColor: mobileColors.greenSoft,
    borderColor: '#C8D8C1',
  },
  statePillClarify: {
    backgroundColor: mobileColors.blueGraySoft,
    borderColor: '#C8DDEC',
  },
  statePillConfirm: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
  },
  statePillReject: {
    backgroundColor: mobileColors.dangerSoft,
    borderColor: '#F2C1B1',
  },
  statePillDegraded: {
    backgroundColor: mobileColors.neutralSoft,
    borderColor: '#CDBFAE',
  },
  statePillText: {
    color: mobileColors.charcoal,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
  },
  entityChip: {
    backgroundColor: mobileColors.quiet,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 999,
    borderWidth: 1,
    color: mobileColors.mutedGray,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  mascotFrame: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    padding: 6,
  },
  mascotFrameSmall: {
    height: 52,
    width: 56,
  },
  mascotFrameMedium: {
    height: 62,
    width: 68,
  },
  mascotFrameLarge: {
    height: 74,
    width: 82,
  },
  mascotFallbackLabel: {
    color: mobileColors.mutedGray,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 10,
    textAlign: 'center',
  },
  mascotMoodIdle: {
    backgroundColor: '#F0E6DA',
    borderColor: mobileColors.borderWarm,
  },
  mascotMoodHello: {
    backgroundColor: '#F0E6DA',
    borderColor: mobileColors.borderWarm,
  },
  mascotMoodThinking: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: mobileColors.borderWarm,
  },
  mascotMoodSuccess: {
    backgroundColor: '#DDE8D8',
    borderColor: '#C8D8C1',
  },
  mascotMoodConfirm: {
    backgroundColor: '#F4E2C8',
    borderColor: '#F3D7B0',
  },
  mascotMoodConfused: {
    backgroundColor: '#DCEAF4',
    borderColor: '#C8DDEC',
  },
  mascotMoodReject: {
    backgroundColor: '#F5D9D0',
    borderColor: '#F2C1B1',
  },
  mascotMoodDegraded: {
    backgroundColor: '#E3DACB',
    borderColor: '#CDBFAE',
  },
  emptyStateCard: {
    alignItems: 'center',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderWarm,
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  emptyStateCopy: {
    alignItems: 'center',
    gap: 6,
  },
  emptyStateTitle: {
    color: mobileColors.charcoal,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 24,
    textAlign: 'center',
  },
  emptyStateBody: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  homeWelcomeCard: {
    alignItems: 'center',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderWarm,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    ...softShadow,
  },
  homeWelcomeCopy: {
    flex: 1,
    gap: 6,
  },
  homeWelcomeTitle: {
    color: mobileColors.charcoal,
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 22,
  },
  homeWelcomeBody: {
    color: mobileColors.mutedGray,
    fontSize: 13,
    lineHeight: 18,
  },
  homeSummaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  homePriorityRow: {
    alignItems: 'flex-start',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  latestChangeCard: {
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 15,
    borderWidth: 1,
    gap: 3,
    padding: 10,
  },
  pendingSummaryCard: {
    backgroundColor: mobileColors.amberSoft,
    borderColor: '#F3D7B0',
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    padding: 14,
    ...softShadow,
  },
  pendingSummaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  quickActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickActionButton: {
    flexGrow: 1,
    minWidth: 98,
  },
  recentCommandRow: {
    alignItems: 'flex-start',
    backgroundColor: mobileColors.white,
    borderColor: mobileColors.borderSubtle,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
});
